constraint:
  wine_glass: 
    lower bound: [-0.5, -0.5, -0.2, -2, -1, -3.14, 0,     0,    0,    0,  0,   0]
    upper bound: [0.5, 0.5, 0.2,   -1, 1, 3.14, 1.57, 1.57, 1.57, 1.57, 2, 1.57]
  stapler: 
    lower bound: [-0.25, -0.25, -0.3, -3, -3, -3, 0,     0,    0,    0,  0,   0]
    upper bound: [0.25, 0.25, 0.5,   3, 3, 3, 1.571, 1.571, 1.571, 1.571, 2, 1.571]

ini: 
  wine_glass: 
    handoff: [0.01, -0.15, -0.1, -1.41, 0.251, 3.14, 0, 0, 0, 0, 0, 0]
    use: [0.01, -0.15, -0.1, -1.41, 0.251, 3.14, 0, 0, 0, 0, 0, 0]
  stapler: 
    handoff: [0.02, -0.13, -0.02, -2.04, 0, 1.57, 0, 0, 0, 0, 1.76, 0]
    use: [0, 0.15, 0, 2.04, 0, -1.57, 0, 0, 0, 0, 1.8, 0]


stapler:
  use:
    thumb: [0.02, 0.038, 0.015]
    index: [0.02, 0.0, 0.015]
    middle: [0.0, 0.0, 0.015]
    ring: [-0.02, 0.0, 0.015]
    little: [-0.04, 0.0, 0.015]
    thumb_vec: [0, 1, 0]
    index_vec: [0, -1, 0]
    middle_vec: [0, -1, 0]
    ring_vec: [0, -1, 0]
    little_vec: [0, -1, 0]


  handoff:
    thumb: [-0.02, -0.012, 0.03]
    index: [-0.02, 0.012, 0.03]
    middle: [0.0, 0.012, 0.03]
    ring: [0.02, 0.012, 0.03]
    little: [0.04, 0.012, 0.03]
    thumb_vec: [0, -1, 0]
    index_vec: [0, 1, 0]
    middle_vec: [0, 1, 0]
    ring_vec: [0, 1, 0]
    little_vec: [0, 1, 0]
  
wine_glass:
  use:
    thumb: [-0.035, 0.0, 0.13]
    index: [0.033, 0.001, 0.16]
    middle: [0.035, 0.008, 0.135]
    ring: [0.032, 0.005, 0.11]
    little: [0.022, 0.001, 0.09]
    thumb_vec: [-1, 0, 0]
    index_vec: [1, 0, 0]
    middle_vec: [1, 0, 0]
    ring_vec: [1, 0, 0]
    little_vec: [1, 0, 0]
    
  handoff:
    thumb: [-0.031, -0.00, 0.15]
    index: [0.028, 0.02, 0.15]
    middle: [0.032, 0.00, 0.15]
    ring: [0.027, -0.02, 0.15]
    little: [0.026, -0.04, 0.15]
    thumb_vec: [-1, 0, 0]
    index_vec: [1, 0, 0]
    middle_vec: [1, 0, 0]
    ring_vec: [1, 0, 0]
    little_vec: [1, 0, 0]